[workspace]
resolver = "3"
members = ["crates/icy_sauce", "crates/icy_sauce_cli"]

[workspace.package]
edition = "2024"
authors = ["Mike Krüger <mkrueger@posteo.de>"]
homepage = "https://github.com/mkrueger/icy_sauce"
repository = "https://github.com/mkrueger/icy_sauce"
license-file = "LICENSE"

[workspace.dependencies]
thiserror = "2.0"
bstr = { version = "1.12", features = ["serde"] }
log = "0.4"
chrono = { version = "0.4", default-features = false }
clap = { version = "4.6", features = ["derive"] }
proptest = "1.11"
serde = { version = "1.0", features = ["derive"] }