name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  run_checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    - name: Check formatting
      run: |
        cargo fmt --all -- --check
        cargo fmt --manifest-path fuzz/Cargo.toml --all -- --check
    - name: Run Clippy
      run: |
        cargo clippy --workspace --all-targets --all-features -- -D warnings
        cargo clippy --manifest-path fuzz/Cargo.toml --all-targets -- -D warnings
    - name: Check documentation
      env:
        RUSTDOCFLAGS: -D warnings
      run: cargo doc --workspace --all-features --no-deps

  test:
    strategy:
      matrix:
        toolchain: [ "1.89.0", "stable" ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.toolchain }}
    - name: Run tests
      run: |
        cargo test --workspace
        cargo test --workspace --all-features